package config

type ConfigKey string

const (
	CFG_APP_ENV  = "APP_ENV"
	CFG_APP_HOST = "APP_HOST"
	CFG_APP_PORT = "APP_PORT"
	CFG_APP_URL  = "APP_URL"

	CFG_GATEWAY = "GATEWAY"
	CFG_STAGE   = "STAGE"

	// postgres
	CFG_POSTGRES_HOST                = "POSTGRES_HOST"
	CFG_POSTGRES_PORT                = "POSTGRES_PORT"
	CFG_POSTGRES_USER                = "POSTGRES_USER"
	CFG_POSTGRES_PASS                = "POSTGRES_PASS"
	CFG_POSTGRES_DB                  = "POSTGRES_DB"
	CFG_POSTGRES_SSLMODE             = "POSTGRES_SSLMODE"
	CFG_POSTGRES_MAX_OPEN_CONNS      = "POSTGRES_MAX_OPEN_CONNS"
	CFG_POSTGRES_MAX_IDLE_CONNS      = "POSTGRES_MAX_IDLE_CONNS"
	CFG_POSTGRES_LIFETIME_IDLE_CONNS = "POSTGRES_LIFETIME_IDLE_CONNS"
	CFG_POSTGRES_LIFETIME_OPEN_CONNS = "POSTGRES_LIFETIME_OPEN_CONNS"
)
